version: 1.12.1

components:    # define all the building-blocks for Pipeline
  - name: DocumentStore
    type: ElasticsearchDocumentStore
    params:
      #embedding_dim: 1024
      host: localhost
      port: 9200
  - name: Retriever #https://docs.haystack.deepset.ai/reference/retriever-api
    type: EmbeddingRetriever #MultihopEmbeddingRetriever
    params:
      document_store: DocumentStore    # params can reference other components defined in the YAML
      top_k: 5
      embedding_model: sentence-transformers/multi-qa-mpnet-base-dot-v1
      model_format: sentence_transformers
      #embedding_model: ada
      #api_key: ....
      #max_seq_len: 1024
      #batch_size: 8
  - name: Reader       # custom-name for the component; helpful for visualization & debugging
    type: FARMReader    # Haystack Class name for the component
    params:
      model_name_or_path: deepset/deberta-v3-base-squad2 #deepset/roberta-base-squad2
      context_window_size: 100
      return_no_answer: true
      confidence_threshold: 0.1
      use_gpu: true
  - name: TextFileConverter
    type: TextConverter
  - name: Preprocessor
    type: PreProcessor
    params:
      split_by: word
      split_length: 1000
      clean_whitespace: false
      clean_empty_lines: false
  - name: FileTypeClassifier
    type: FileTypeClassifier

pipelines:
  - name: query    # a sample extractive-qa Pipeline
    nodes:
      - name: Retriever
        inputs: [Query] # query_classifier
      - name: Reader
        inputs: [Retriever]
  - name: indexing
    nodes:
      - name: TextFileConverter
        inputs: [File]
      - name: Preprocessor
        inputs: [TextFileConverter]
      - name: Retriever
        inputs: [Preprocessor]
      - name: DocumentStore
        inputs: [Retriever]