name: Minor Version Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (in the format of v1.10.x) '
        required: true

## Debug
#on:
#  push:
#    branches:
#      - readme_release_workflow
#    inputs:
#      version:
#        default: v1.10.x
#        description: 'Version to release (in the format of v1.10.x) '
#        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Set up Python 3.8.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydoc-markdown==4.5.1

      - name: Convert version name to regular semver (e.g. v1.10.x -> v1.10.0)
        id: regular_semver
        env:
          version: ${{github.event.inputs.version}}
        run: |
            echo $version | sed -e 's/x$//' | { var=$(cat); echo "VERSION=v${var}0" >> $GITHUB_ENV; }
            echo $version | sed -e 's/x$//'

      - name: Save short version name
        env:
          version: $VERSION
        run: |
          echo $VERSION | sed -e 's/\.[0-9]*$//' | { var=$(cat); echo "VERSION_SHORT=v${var}" >> $GITHUB_ENV; }
          echo $VERSION | sed -e 's/\.[0-9]*$//'

      - name: Create new version branch
        run: |
          git checkout -b ${{github.event.inputs.version}}
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git push -u origin ${{github.event.inputs.version}}

      # Note that patch versions all sync to the one readme minor version
      # e.g. Haystack 1.9.1 and 1.9.2 both map to Readme 1.9
      - name: Release Readme version
        run: |
          git checkout ${{github.event.inputs.version}}
          python ./.github/utils/release_docs.py --version "$VERSION_SHORT" --key ${{ secrets.README_API_KEY }}
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update API docs headers and readme_api_sync.yml to sync to new version"
          git push

      - name: Edit category versions in API pydoc configs
        run: |
          git checkout ${{github.event.inputs.version}}
          python ./.github/utils/change_api_category_id.py --version "$VERSION_SHORT" --key ${{ secrets.README_API_KEY }}
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update API docs headers and readme_api_sync.yml to sync to new version"
          git push

      - name: Edit sync version in new branch
      - run: |
          git checkout ${{github.event.inputs.version}}
          python ./.github/utils/change_api_sync_version.py --version "$VERSION"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Change version in readme_api_sync.yml to sync to new version"
          git push

      # TODO Can this actually commit changes to main? Do we want this?
      - name: Edit version in main
      - run: |
          git checkout main
          python ./.github/utils/change_api_sync_version.py --version "$VERSION" --unstable
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Change version in readme_api_sync.yml to sync to new version"
          git push



