name: Sync API docs from Haystack to Readme

on:
  push:
    branches:
      - main
      # release branches have the form v1.9.x
      - 'v[0-9].*[0-9].x'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Set up Python 3.8.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydoc-markdown==4.5.1

      - name: Generate API docs
        run: ./.github/utils/pydoc-markdown.sh

      - name: Compare current version with latest
        uses: madhead/semver-utils@latest
        id: version
        with:
          # Version being built
          # TODO UNCOMMENT
          version: v1.10.0
          # Compare to latest
          compare-to: ${{ steps.latest-version.outputs.release }}

      - name: Save short version name
        env:
          version: ${{steps.version.outputs.release}}
        run: |
          echo $version | sed -e 's/\.[0-9]*$//' | { var=$(cat); echo "VERSION_SHORT=v${var}" >> $GITHUB_ENV; }
          echo $version | sed -e 's/\.[0-9]*$//'

      - name: Github Action (API sync)
        uses: readmeio/rdme@7.2.0
        env:
          README_API_KEY: ${{ secrets.README_API_KEY }}
        with:
          rdme: docs ./docs/_src/api/api/temp --key="$README_API_KEY" --version="$VERSION_SHORT"
      # TODO NEED TO HANDLE PUSHES TO MAIN