name: Trying out Version Actions

on:
  push:
    branches:
      - readme_release

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:

      - name: Compare current version with latest
        uses: madhead/semver-utils@latest
        id: version
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # Version being built
          version: ${{  github.ref_name }}
          # Compare to latest
          compare-to: ${{ steps.latest-version.outputs.release }}

      - name: Use latest
        if: steps.version.outputs.comparison-result == '>'
        run: |
          echo ${{ steps.version.outputs.comparison-result }};
          echo ${{ steps.latest-version.outputs.release }};