name: Trying out Version Actions

on:
  push:
    branches:
      - readme_release

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get latest version of Haystack
        id: latest-version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          excludes: prerelease, draft

      - name: Compare current version with latest
        uses: madhead/semver-utils@latest
        id: version
        with:
          # Version being built
          version: v1.8.0 #XXXXXXXXXXXXXXX
          # Compare to latest
          compare-to: ${{ steps.latest-version.outputs.release }}

      - name: Save short version name
        env:
          version: ${{steps.version.outputs.release}}
        run: |
          echo $version
          echo "$version" | sed -e 's/\.[0-9]*$//' | echo "version_short=$1" >> $GITHUB_ENV

      - name: Print short version name
        run: echo ${{ env.version_short }}


      - run: |
          echo "${{ steps.version.outputs.release }}"           # 1.2.3
          echo "${{ steps.version.outputs.major }}"             # 1
          echo "${{ steps.version.outputs.minor }}"             # 2
          echo "${{ steps.version.outputs.patch }}"             # 3
          echo "${{ steps.version.outputs.build }}"             # 42.24
          echo "${{ steps.version.outputs.build-parts }}"       # 2
          echo "${{ steps.version.outputs.build-0 }}"           # 42
          echo "${{ steps.version.outputs.build-1 }}"           # 24
          echo "${{ steps.version.outputs.comparison-result }}" # <
          echo "${{ steps.version.outputs.satisfies }}"         # true
          echo "${{ steps.version.outputs.inc-major }}"         # 2.0.0
          echo "${{ steps.version.outputs.inc-premajor }}"      # 2.0.0-0
          echo "${{ steps.version.outputs.inc-minor }}"         # 1.3.0
          echo "${{ steps.version.outputs.inc-preminor }}"      # 1.3.0-0
          echo "${{ steps.version.outputs.inc-patch }}"         # 1.2.4
          echo "${{ steps.version.outputs.inc-prepatch }}"      # 1.2.4-0
          echo "${{ steps.version.outputs.inc-prerelease }}"    # 1.2.4-0

      - name: Release Haystack-Readme version
        id: variables
        env:
            VERSION: v${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
        run: |
          echo $VERSION

      - name: Use latest
        if: steps.version.outputs.comparison-result == '>'
        run: |
          echo ${{ steps.version.outputs.comparison-result }};
          echo ${{ steps.latest-version.outputs.release }};

      - name: Compare current version with latest
        uses: madhead/semver-utils@latest
        id: versionx
        env:
          VERSIONX: "v${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}"
        with:
          # Version being built
          version: ${{  github.ref_name }}
          # Compare to latest
          compare-to: ${{ steps.latest-version.outputs.release }}

      - name: Print everything
        run: |
          echo ${{ steps.version.outputs.comparison-result }};
          echo ${{ steps.latest-version.outputs.release }};
          echo ${{ github.repository }};
          echo ${{ github.ref_name }};
          echo "v${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}";