name: Trying out Version Actions

on:
  push:
    branches:
      - readme_release

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get latest version of Haystack
        id: latest-version
        uses: pozetroninc/github-action-get-latest-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repository: ${{ github.repository }}
          excludes: prerelease, draft

      - name: Compare current version with latest
        uses: madhead/semver-utils@latest
        id: version
        with:
          # Version being built
          version: ${{  github.ref_name }}
          # Compare to latest
          compare-to: ${{ steps.latest-version.outputs.release }}

      - name: Use latest
        if: steps.version.outputs.comparison-result == '>'
        run: |
          echo ${{ steps.version.outputs.comparison-result }};
          echo ${{ steps.latest-version.outputs.release }};

      - name: Compare current version with latest
        uses: madhead/semver-utils@latest
        id: versionx
        env:
          VERSION: v${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
        with:
          # Version being built
          version: ${{  github.ref_name }}
          # Compare to latest
          compare-to: ${{ steps.latest-version.outputs.release }}

      - name: Print everything
        run: |
          echo ${{ steps.version.outputs.comparison-result }};
          echo ${{ steps.latest-version.outputs.release }};
          echo ${{ github.repository }};
          echo ${{ github.ref_name }};
          echo "$VERSION";